# Data
DATASET_RAW = '../data/dataset_raw.csv'
DATASET_PROCESSED = '../data/dataset_processed.csv'
DATASET_LEAN = '../data/dataset_lean.csv'
DATASET_DUMMIES = '../data/dataset_dummies.csv'
DATASET_TRANSFORMED = '../data/dataset_transformed.csv'
DATASET_CLUSTERED = '../data/dataset_clustered.csv'
DATASET_DEPLOY_CLASSIFICATION = '../data/dataset_deploy_classification.csv'
DATASET_DEPLOYED_CLASSIFICATION = '../data/dataset_deployed_classification.csv'

# Models
MODEL_CLASSIFICATION_JOBLIB = '../models/model_classification.joblib'
MODEL_CLASSIFICATION_PKL = '../models/model_classification.pkl'

# Reports
EDA_0 = '../reports/eda_0.html'
EDA_1 = '../reports/eda_1.html'

# Values
RANDOM_STATE = 42

# Images Outputs
OUTPUT_SCHEDULE = '../images/output_schedule.png'

# Images Illustrations
WALLPAPER = '../images/wallpaper.png'
BOXPLOT = '../images/boxplot.png'
SCATTERPLOT = '../images/scatterplot.png'
HISTPLOT = '../images/histplot.png'
KDEPLOT = '../images/kdeplot.png'
HEATMAP = '../images/heatmap.png'
PAIRPLOTS = '../images/pairplots.png'
ACCURACY = '../images/accuracy.png'
PRECISION = '../images/precision.png'
RECALL = '../images/recall.png'
F1_SCORE = '../images/f1_score.png'
ROC_AUC = '../images/roc_auc.png'
AUPRC = '../images/auprc.png'
AP = '../images/ap.png'
CONFUSION_MATRIX = '../images/confusion_matrix.png'
TIME = '../images/time.png'
MAE = '../images/mae.png'
MSE = '../images/mse.png'
RMSE = '../images/rmse.png'
R2 = '../images/r2.png'
ELBOW_METHOD = '../images/elbow_method.png'
SILHOUETTE_METHOD = '../images/silhouette_method.png'
DUMMY = '../images/dummy.png'
CLASSIFICATION_TREE = '../images/classification_tree.png'
LOGISTIC_REGRESSION = '../images/logistic_regression.png'
NAIVE_BAYES = '../images/naive_bayes.png'
KNN = '../images/knn.png'
SVM = '../images/svm.png'
LINEAR_REGRESSION = '../images/linear_regression.png'
POLYNOMIAL_REGRESSION = '../images/polynomial_regression.png'
REGRESSION_TREE = '../images/regression_tree.png'
KNR = '../images/knr.png'
RANDOM_FOREST_REGRESSOR = '../images/random_forest_regressor.png'
XGBOOST_REGRESSOR = '../images/xgboost_regressor.png'
K_MEANS = '../images/k_means.png'
MEAN_SHIFT = '../images/mean_shift.png'
DBSCAN = '../images/dbscan.png'
ONE_HOT_ENCODER = '../images/one_hot_encoder.png'
STANDARD_SCALER = '../images/standard_scaler.png'
POWER_TRANSFORMATION = '../images/power_transformation.png'
MIN_MAX_SCALER = '../images/min_max_scaler.png'
ROBUST_SCALER = '../images/robust_scaler.png'
PCA = '../images/pca.png'
ROS = '../images/ros.png'
RUS = '../images/rus.png'
PIPELINE = '../images/pipeline.png'
K_FOLD = '../images/k_fold.png'
STRATIFIED_K_FOLD = '../images/stratified_k_fold.png'
GRID_SEARCH = '../images/grid_search.png'